# Generated by Django 5.2 on 2025-05-07 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0002_airportmodel_latitude_airportmodel_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airportmodel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='airportmodel',
            name='longitude',
        ),
    ]
